#!/bin/bash

sudo cd ~/
echo "1. Creating working directory:" $(pwd)
sudo rm -rf ~/ubuntu-multi-monitor-fix
sudo mkdir ~/ubuntu-multi-monitor-fix
cd ~/ubuntu-multi-monitor-fix
echo
echo "2. Cloning fix source to directory:" $(pwd)
sudo git clone https://gist.github.com/7688785.git fix-source
cd ~/ubuntu-multi-monitor-fix/fix-source
echo
echo "3. Building patched Xinerama (X11 add-in) library:"
sudo rm -f ./libXinerama.so
sudo gcc -fPIC -O2 -shared -o libXinerama.so fakexinerama.c -lX11
echo
echo "4. Creating soft link to library (for major number compatibility):"
sudo rm -f ./libXinerama.so.1
sudo ln -s ./libXinerama.so ./libXinerama.so.1
echo
echo "5. Copying patched Xinerama libary in default searh path: /usr/local/lib"
sudo cp ./libXinerama.so /usr/local/lib/
sudo cp ./libXinerama.so.1 /usr/local/lib/

echo "6. Restarting the X server..."
sudo restart lightdm

#Section "ServerFlags"
#	Option "xinerama" "true"
#	Option "DefaultServerLayout" ""X.org Configured"
#EndSection







